language: node_js
node_js:
    - "node"
script: npm test
sudo: true
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y firefox
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm install