language: node_js
node_js:
    - "node"
script: npm test
sudo: true
before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sudo apt-get -qq update
    - sudo apt-get install -y chromium-browser
    - sh -e /etc/init.d/xvfb start
